### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [shabane/illusion#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by shabane** [comment]
hello.
so many *thank* you, for your suggest.
and thank you for your **awesome repo**
i added the license. the license is **beerware**, do you think this is good ?
i choose it because i liked this license ideas.


thank you again and again :)
